# version format
version: '{build}' # prefer not to use the version number for the build number

# branches to build
branches:
  # whitelist
  only:
    - will/yak-ci-tidy # TODO: switch back to master after testing

# environment variables
environment:
  # current major.minor.patch version number
  assembly_version: '1.0.0'
  # package version with prerelease identifiers
  yak_package_version: $(assembly_version)-dev.$(appveyor_build_number)

# Maximum number of concurrent jobs for the project
max_jobs: 1

# Build worker image (VM template)
image: Visual Studio 2017

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
  - nuget restore

build:
  parallel: true                  # enable MSBuild parallel builds
  project: GhCanvasViewport.sln      # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: normal

# patch assembly info
assembly_info:
  patch: true
  file: 'Properties\AssemblyInfo.cs'
  assembly_version: $(assembly_version) # required, otherwise defaults to $(appveyor_build_version)
  # assembly_file_version: '{version}'
  assembly_informational_version: $(yak_package_version)

# publish prerelease build to yak
deploy_script:
  - ps: .\script\deploy.ps1
