version: '{build}'
image: Visual Studio 2019
configuration: Release

# set version number for plug-in and yak package
environment:
  assembly_version: '1.0.1'
  yak_package_version: $(assembly_version)

assembly_info:
  patch: true
  file: 'Properties\AssemblyInfo.cs'
  assembly_version: $(assembly_version)
  assembly_informational_version: $(yak_package_version)

# compile plug-in
before_build:
  - nuget restore

build:
  project: GhCanvasViewport.sln
  verbosity: minimal

# build yak package
before_deploy:
  - curl -fSLo yak.exe https://files.mcneel.com/yak/tools/latest/yak.exe
    && yak.exe version
    && copy bin\GhCanvasViewport.gha dist
    && cd dist
    && ..\yak.exe build

# publish to rhino package manager (master only)
deploy_script:
  - IF "%APPVEYOR_REPO_BRANCH%"=="master" ( yak.exe push dist\*.yak )
